name: CI Build

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  mainline-build:
    runs-on: arlaneenalra/watcom-docker


    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Build
        run: make -j 5 WATCOM= 
      
